# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
    paths: 
      - manifest.json
      - .github/workflows/node.js.yml
  pull_request:
    branches: [ main ]
    paths:
      - manifest.json
      - .github/workflows/node.js.yml

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: exit 0
    - run: exit 1; exit0
    - run: foobar
    - run: npm install --global web-ext
    - run: web-ext build
    - run: web-ext sign --api-key=${{ secrets.FIREFOXAMOISSUER }} --api-secret=${{ secrets.FIREFOXAMOSECRET }} --id={0948dc04-cbab-42e8-8ee2-15feba5a54a2} 
    - name: Archive Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: web-ext-artifacts
        path: |
          web-ext-artifacts
